# roles/haproxy/tasks/main.yml
---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Ensure HAProxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - Restart HAProxy

- name: Allow traffic on HAProxy ports
  ufw:
    rule: allow
    port: 3306
    proto: tcp

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted
