---
- name: Configure MariaDB Galera Cluster
  hosts: galera-cluster-nodes
  become: true
  pre_tasks:
    - name: Ensure /etc/mysql/conf.d directory exists
      file:
        path: /etc/mysql/conf.d
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'
  roles:
    - mrlesmithjr.mariadb_galera_cluster
  vars:
    mariadb_galera_cluster_name: my_cluster
    mariadb_galera_cluster_nodes: "{{ groups['galera-cluster-nodes'] }}"
    mariadb_galera_cluster_bootstrap_node: ip-172.26.4.253
    galera_mysql_first_node: ip-172.26.4.253
    galera_cluster_nodes: "{{ groups['galera-cluster-nodes'] }}"
    galera_cluster_bind_interface: ens5
    #mariadb_upgrade: true  # Add this line to allow upgrading MariaDB

- name: Bootstrap and start MariaDB Galera Cluster
  hosts: galera-cluster-nodes
  become: true
  tasks:
    - name: Stop MariaDB on all nodes
      systemd:
        name: mariadb
        state: stopped
      ignore_errors: yes

    - name: Bootstrap the primary node
      command: galera_new_cluster
      when: inventory_hostname == "ip-172.26.4.253"

    - name: Start MariaDB on primary node
      systemd:
        name: mariadb
        state: started
      when: inventory_hostname == "ip-172.26.4.253"

    - name: Wait for primary node to start
      wait_for:
        host: ip-172.26.4.253
        port: 3306
        state: started
      when: inventory_hostname != "ip-172.26.4.253"

    - name: Start MariaDB on non-primary nodes
      systemd:
        name: mariadb
        state: started
      when: inventory_hostname != "ip-172.26.4.253"

    - name: Check MariaDB status on all nodes
      command: systemctl status mariadb
      register: mariadb_status
      ignore_errors: yes

    - debug:
        var: mariadb_status

- name: Verify Galera Cluster Status
  hosts: galera-cluster-nodes
  become: true
  tasks:
    - name: Check wsrep_cluster_size
      shell: "mysql -u root -e 'SHOW STATUS LIKE \"wsrep_cluster_size\";'"
      register: wsrep_cluster_size
      ignore_errors: yes

    - debug:
        msg: "{{ inventory_hostname }}: wsrep_cluster_size is {{ wsrep_cluster_size.stdout }}"

