---
- name: Configure MariaDB Galera Cluster
  hosts: galera-cluster-nodes
  become: true
  pre_tasks:
    - name: Ensure /etc/mysql/conf.d directory exists
      file:
        path: /etc/mysql/conf.d
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'

  roles:
    - mrlesmithjr.mariadb_galera_cluster

  vars:
    mariadb_galera_cluster_name: my_cluster
    mariadb_galera_cluster_nodes: "{{ groups['galera-cluster-nodes'] }}"
    mariadb_galera_cluster_bootstrap_node: ip-172.26.4.253
    galera_mysql_first_node: ip-172.26.4.253
    galera_cluster_nodes: "{{ groups['galera-cluster-nodes'] }}"
    galera_cluster_bind_interface: ens5

  tasks:
    - name: Create lending_service database
      mysql_db:
        name: lending_service
        state: present
        login_user: root
        login_password: ""  # Update this if the root user has a password
        login_host: localhost

    - name: Copy schema file to target hosts
      copy:
        src: /home/gkipngok/ansible-mariadb-galera/db_schema/sample_schema.sql  # Update this path to the location of your schema file on the Ansible control machine
        dest: /tmp/sample_schema.sql

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started

    - name: Restore schema from backup file using MySQL client
      shell: mysql -u root lending_service < /tmp/sample_schema.sql

    #- name: Configure HAProxy Load Balancer
     # hosts: loadbalancer
      #become: true
      #roles:
       # - haproxy
